- alias: set_freshairfilter_mode
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_select.set_freshairfilter_mode
  action:
    service: smartthinq.lge_ref_set_freshairfilter_mode
    data_template:
      entity_id: climate.refrigerator
      freshairfilter_mode: >
          {% if is_state("input_select.set_freshairfilter_mode", "파워") %}
          파워
          {%-elif is_state("input_select.set_freshairfilter_mode", "자동") %}
          자동
          {%-elif is_state("input_select.set_freshairfilter_mode", "꺼짐") %}
          꺼짐
          {% endif %}
      
- alias: set_input_select_freshairfilter_mode
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.ref_freshairfilter_state
  action:
    - service: automation.turn_off
      entity_id: automation.set_freshairfilter_mode
    - service: input_select.select_option
      data_template:
        entity_id: input_select.set_freshairfilter_mode    
        option: "{{states.climate.refrigerator.attributes.freshairfilter_state}}"
    - service: automation.turn_on
      entity_id: automation.set_freshairfilter_mode