- alias: set_freezer_temperature
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_number.set_freezer_temp
  action:
    service: smartthinq.lge_ref_set_freezer_temperature
    data_template:
      entity_id: climate.refrigerator
      freezer_temperature: "{{ trigger.to_state.state | int }}"
            
- alias: set_input_number_freezer_temperature
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.freezer_temperature
  action:
    - service: automation.turn_off
      entity_id: automation.set_freezer_temperature
    - service: input_number.set_value
      data_template:
        entity_id: input_number.set_freezer_temp
        value: "{{states.climate.refrigerator.attributes.freezer_temperature}}"
    - service: automation.turn_on
      entity_id: automation.set_freezer_temperature